name: Handle a PR comment
run-name: Handle slash command in a PR comment`

on:
  # GitGitGadget's GitHub App is expected to trigger this on `issue_comment` events
  # that have the `action` set to `created` or `edited`
  workflow_dispatch:
    inputs:
      pr-comment-url:
        description: 'URL of the PR comment to handle'
        required: true

env:
  PR_COMMENT_URL: ${{ inputs.pr-comment-url }}

concurrency:
  group: ${{ github.workflow }}-${{ inputs.pr-comment-url }}

jobs:
  handle-pr-comment:
    runs-on: ubuntu-latest
    if: vars.CONFIG != ''

    steps:
    - uses: actions/create-github-app-token@v2
      id: pr-repo-token
      with:
        app-id: ${{ secrets.GITGITGADGET_GITHUB_APP_ID }}
        private-key: ${{ secrets.GITGITGADGET_GITHUB_APP_PRIVATE_KEY }}
        owner: ${{ fromJSON(vars.CONFIG).repo.owner }}
        repositories: ${{ fromJSON(vars.CONFIG).repo.name }}
    - uses: actions/create-github-app-token@v2
      if: ${{ contains(fromJSON(vars.CONFIG).repo.owners, fromJSON(vars.CONFIG).repo.baseOwner) }}
      id: upstream-repo-token
      with:
        app-id: ${{ secrets.GITGITGADGET_READONLY_GITHUB_APP_ID }}
        private-key: ${{ secrets.GITGITGADGET_READONLY_GITHUB_APP_PRIVATE_KEY }}
        owner: ${{ fromJSON(vars.CONFIG).repo.baseOwner }}
        repositories: ${{ fromJSON(vars.CONFIG).repo.name }}
    - uses: actions/create-github-app-token@v2
      if: ${{ contains(fromJSON(vars.CONFIG).repo.owners, fromJSON(vars.CONFIG).repo.testOwner) }}
      id: test-repo-token
      with:
        app-id: ${{ secrets.GITGITGADGET_READONLY_GITHUB_APP_ID }}
        private-key: ${{ secrets.GITGITGADGET_READONLY_GITHUB_APP_PRIVATE_KEY }}
        owner: ${{ fromJSON(vars.CONFIG).repo.testOwner }}
        repositories: ${{ fromJSON(vars.CONFIG).repo.name }}
    - uses: gitgitgadget/gitgitgadget/check-run@v1
      with:
        config: ${{ vars.CONFIG }}
        pr-repo-token: ${{ steps.pr-repo-token.outputs.token }}
        upstream-repo-token: ${{ steps.upstream-repo-token.outputs.token }}
        test-repo-token: ${{ steps.test-repo-token.outputs.token }}
        pr-url: ${{ env.PR_COMMENT_URL }}
        name: handle_pr_comment
        title: Handle PR comment
        summary: Handling PR comment ${{ env.PR_COMMENT_URL }}
        text: This handles ${{ env.PR_COMMENT_URL }}, see ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} for details.
    - uses: gitgitgadget/gitgitgadget/handle-pr-comment@v1
      with:
        config: ${{ vars.CONFIG }}
        pr-repo-token: ${{ steps.pr-repo-token.outputs.token }}
        upstream-repo-token: ${{ steps.upstream-repo-token.outputs.token }}
        test-repo-token: ${{ steps.test-repo-token.outputs.token }}
        smtp-host: '${{ fromJSON(vars.CONFIG).mail.smtpHost }}'
        smtp-user: '${{ fromJSON(vars.CONFIG).mail.smtpUser }}'
        smtp-pass: "${{ secrets.GITGITGADGET_SMTP_PASS }}"
        pr-comment-url: ${{ env.PR_COMMENT_URL }}
