name: Handle a PR comment
run-name: Handle slash command in a PR comment`

on:
  # GitGitGadget's GitHub App is expected to trigger this on `issue_comment` events
  # that have the `action` set to `created` or `edited`
  workflow_dispatch:
    inputs:
      pr-comment-url:
        description: 'URL of the PR comment to handle'
        required: true

env:
  PR_COMMENT_URL: ${{ inputs.pr-comment-url }}

jobs:
  handle-pr-comment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/create-github-app-token@v1
      id: gitgitgadget-git-token
      with:
        app-id: ${{ secrets.GITGITGADGET_GITHUB_APP_ID }}
        private-key: ${{ secrets.GITGITGADGET_GITHUB_APP_PRIVATE_KEY }}
        owner: gitgitgadget
        repositories: git
    - uses: actions/create-github-app-token@v1
      id: git-git-token
      with:
        app-id: ${{ secrets.GITGITGADGET_GIT_GITHUB_APP_ID }}
        private-key: ${{ secrets.GITGITGADGET_GIT_GITHUB_APP_PRIVATE_KEY }}
        owner: git
        repositories: git
    - uses: actions/create-github-app-token@v1
      id: dscho-git-token
      with:
        app-id: ${{ secrets.GITGITGADGET_GIT_GITHUB_APP_ID }}
        private-key: ${{ secrets.GITGITGADGET_GIT_GITHUB_APP_PRIVATE_KEY }}
        owner: dscho
        repositories: git
    - uses: gitgitgadget/gitgitgadget/handle-pr-comment@v1
      with:
        pr-repo-token: ${{ steps.gitgitgadget-git-token.outputs.token }}
        upstream-repo-token: ${{ steps.git-git-token.outputs.token }}
        test-repo-token: ${{ steps.dscho-git-token.outputs.token }}
        smtp-host: smtp.gmail.com
        smtp-user: gitgitgadget@gmail.com
        smtp-pass: "${{ secrets.GITGITGADGET_SMTP_PASS }}"
        pr-comment-url: ${{ env.PR_COMMENT_URL }}
